# API Configuration
api:
  angel_one:
    token_master_url: "https://margincalculator.angelbroking.com/OpenAPI_File/files/OpenAPIScripMaster.json"

# Market Configuration
market:
  trading_hours:
    start: "09:15"  # IST
    end: "15:30"    # IST
  pre_market:
    start: "09:00"
    end: "09:15"
  post_market:
    start: "15:30"
    end: "15:45"

# Database Configuration
database:
  default_path: "nfo_derivatives_hub.duckdb"  # Central hub for NFO derivatives data (tokens, historical, and spot values)

# Token Types
token_types:
  futures: "FUTURES"
  equity: "EQUITY"
  options: "OPTIONS"

# Instrument Types
instrument_types:
  futures_stock: "FUTSTK"
  options_stock: "OPTSTK"

# Exchange Segments
exchange_segments:
  nfo: "NFO"
  nse: "NSE"

# Date Formats
date_formats:
  expiry: "%d%b%Y"
  db_date: "%Y-%m-%d"

# Equity Market Data Configuration
equity_market_data:
  start_date: "2000-01-01 09:15"  # Historical data start date
  rate_limiting:
    request_delay: 0.25  # Seconds between API requests
    batch_delay: 1  # Seconds between batches
  default_interval: "ONE_DAY"  # Default interval for historical data
  intervals:
    minute: "ONE_MINUTE"
    five_minutes: "FIVE_MINUTE"
    fifteen_minutes: "FIFTEEN_MINUTE"
    thirty_minutes: "THIRTY_MINUTE"
    hour: "ONE_HOUR"
    day: "ONE_DAY"

# Real-time Market Data Configuration
realtime_market_data:
  mode: "FULL"  # Mode for getMarketData API (FULL, OHLC, LTP)
  max_tokens_per_request: 50  # Maximum number of tokens per API request
  rate_limiting:
    request_delay: 1.0  # Seconds between API requests (rate limit is 1 request per second)
  refresh_interval: 60  # Seconds between real-time data refreshes
  default_options:
    include_equity: true
    include_futures: true
    include_options: false 