# API Configuration
api:
  angel_one:
    token_master_url: "https://margincalculator.angelbroking.com/OpenAPI_File/files/OpenAPIScripMaster.json"

# Market Configuration
market:
  trading_hours:
    start: "09:15"  # IST
    end: "19:30"    # IST
  pre_market:
    start: "09:00"
    end: "09:15"
  post_market:
    start: "19:30"
    end: "19:45"

# Database Configuration
database:
  default_path: "nfo_derivatives_hub.duckdb"  # Central hub for NFO derivatives data (tokens, historical, and spot values)

# Token Types
token_types:
  futures: "FUTURES"
  equity: "EQUITY"
  options: "OPTIONS"

# Instrument Types
instrument_types:
  futures_stock: "FUTSTK"
  options_stock: "OPTSTK"

# Exchange Segments
exchange_segments:
  nfo: "NFO"
  nse: "NSE"

# Date Formats
date_formats:
  expiry: "%d%b%Y"
  db_date: "%Y-%m-%d"

# Technical Indicators Configuration
technical_indicators:
  default_indicator: "sma"  # Default indicator type
  default_period: 200  # Default period for indicators (e.g., 200 days for SMA)
  indicators:
    sma:
      periods: [50, 100, 200]  # Available periods for SMA
      description: "Simple Moving Average"
    ema:
      periods: [20, 50, 200]  # Available periods for EMA
      description: "Exponential Moving Average"
    rsi:
      periods: [14, 21]  # Available periods for RSI
      description: "Relative Strength Index"
    volatility:
      periods: [21, 200]  # Available periods for historical volatility
      description: "Historical Volatility (Standard Deviation of Returns)"
  max_fetch_multiplier: 1.5  # Fetch 1.5x the required periods for safe calculation
  batch_size: 50  # Number of tokens to process in each batch
  enable_by_default: true  # Whether to calculate indicators by default after fetching historical data

# Equity Market Data Configuration
equity_market_data:
  start_date: "2000-01-01 09:15"  # Historical data start date
  rate_limiting:
    request_delay: 0.25  # Seconds between API requests
    batch_delay: 1  # Seconds between batches
  default_interval: "ONE_DAY"  # Default interval for historical data
  intervals:
    minute: "ONE_MINUTE"
    five_minutes: "FIVE_MINUTE"
    fifteen_minutes: "FIFTEEN_MINUTE"
    thirty_minutes: "THIRTY_MINUTE"
    hour: "ONE_HOUR"
    day: "ONE_DAY"

# Real-time Market Data Configuration
realtime_market_data:
  mode: "FULL"  # Mode for getMarketData API (FULL, OHLC, LTP)
  max_tokens_per_request: 50  # Maximum number of tokens per API request
  rate_limiting:
    request_delay: 1.0  # Seconds between API requests (rate limit is 1 request per second)
  refresh_interval: 60  # Seconds between real-time data refreshes
  default_options:
    include_equity: true
    include_futures: true
    include_options: false 